config/routes.rb
Rails.application.routes.draw do
  get 'user/index'

  get 'user/show'

  get 'user/new'

  get 'user/edit'

  get 'trip/index'

  get 'trip/show'

  get 'trip/new'

  get 'trip/edit'

  get 'itinerary/index'

  get 'itinerary/show'

  get 'itinerary/new'

  get 'itinerary/edit'
  
  get 'test'  => 'emailprocessor#test'
  
  post 'initialize' => 'emailprocessor#initialize'
  
  post 'process' => 'emailprocessor#process'

  resources :users do
    resources :itinerary do
      resources :trip
    end
  end
  
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :itinerary
end

app/controllers/trip.rb
class Trip
    def type
        raise NotImplementedError, 'Ask type'
    end
    def carrier
        raise NotImplementedError, 'Ask carrier'
    end
    def confirmationNumber
        raise NotImplementedError, 'Missing confirmationNumber'
    end
    def seatNumber
        raise NotImplementedError, 'Ask type'
    end
    def startTime
        raise NotImplementedError, 'Ask type'
    end
    def endTime
        raise NotImplementedError, 'Ask type'
    end
    def startDate
        raise NotImplementedError, 'Ask type'
    end
    def endDate
        raise NotImplementedError, 'Ask type'
    end
    def startLocation
        raise NotImplementedError, 'Ask type'
    end
    def endLocation
        raise NotImplementedError, 'Ask type'
    end
end

class PlaneTrip < Trip
    def type
        'Plane'
    end
end

class TrainTrip < Trip
    def type
        'Train'
    end
end

class BusTrip < Trip
    def type
        'Bus'
    end
end
    
    
    
    

app/controllers/trip_controller.rb
class TripController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @itinerary = Itinerary.find(params[:itinerary_id])
    
    @trip = @itinerary.trips
  end

  def show
    @itinerary = Itinerary.find(params[:itinerary_id])
    
    @trip = @itinerary.trips.find(params[:id])
  end

  def new
    @itinerary = Itinerary.find(params[:itinerary_id])
    
    @trip = @itinerary.trips.build
  end
  
  def create
    @itinerary = Itinerary.find(params[:itinerary_id])
    
    @trip = @itinerary.trips.build(params.require(:trip).permit(:confirmationnumber, :starttime, :startdate, :endtime, :enddate, :seatnumber, :carrier, :type)
    if @trip.save
    # Save the trip successfully
      redirect_to itinerary_trip_url(@itinerary, @trip)
    else
      render :action => "new"
    end

  def edit
  end
  
  
  
  
  
end

app/helpers/trip_helper.rb
module TripHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :confirmationnumber %>
    <%= form.text_field :confirmationnumber, id: :trip_confirmationnumber %>
  </div>

  <div class="field">
    <%= form.label :starttime %>
    <%= form.text_field :starttime, id: :trip_starttime %>
  </div>

  <div class="field">
    <%= form.label :startdate %>
    <%= form.text_field :startdate, id: :trip_startdate %>
  </div>

  <div class="field">
    <%= form.label :endtime %>
    <%= form.text_field :endtime, id: :trip_endtime %>
  </div>

  <div class="field">
    <%= form.label :enddate %>
    <%= form.text_field :enddate, id: :trip_enddate %>
  </div>

  <div class="field">
    <%= form.label :seatnumber %>
    <%= form.text_field :seatnumber, id: :trip_seatnumber %>
  </div>

  <div class="field">
    <%= form.label :carrier %>
    <%= form.text_field :carrier, id: :trip_carrier %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :trip_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips from <%= @itinerary.title %></h1>

<table>
  <thead>
    <tr>
      <th>Confirmationnumber</th>
      <th>Starttime</th>
      <th>Startdate</th>
      <th>Endtime</th>
      <th>Enddate</th>
      <th>Seatnumber</th>
      <th>Carrier</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.confirmationnumber %></td>
        <td><%= trip.starttime %></td>
        <td><%= trip.startdate %></td>
        <td><%= trip.endtime %></td>
        <td><%= trip.enddate %></td>
        <td><%= trip.seatnumber %></td>
        <td><%= trip.carrier %></td>
        <td><%= trip.type %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= form_for([@itinerary, @trip]) do |f| %>
    <% if @trip.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@trip.errors.count, "error")%> prohibited this trip from being saved:</h2>
            <ul>
            <% @trip.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <p>
            <%= f.label :Confirmationnumber %>
            <br />
            <%= f.text_field :confirmationnumber %>
        </p>
        <p>
            <%= f.label :Starttime %>
            <br />
            <%= f.text_field :starttime %>
        </p>
        <p>
            <%= f.label :Startdate %>
            <br />
            <%= f.text_field :startdate %>
        </p>
        <p>
            <%= f.label :Endtime %>
            <br />
            <%= f.text_field :endtime %>
        </p>
        <p>
            <%= f.label :Enddate %>
            <br />
            <%= f.text_field :enddate %>
        </p>
        <p>
            <%= f.label :Seatnumber %>
            <br />
            <%= f.text_field :seatnumber %>
        </p>
        <p>
            <%= f.label :Carrier %>
            <br />
            <%= f.text_field :carrier %>
        </p>
        <p>
            <%= f.label :Type %>
            <br />
            <%= f.text_field :type %>
        </p>
    </div>
    <div class="actions">
    <%= f.submit %>
    </div>
    <% end %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Confirmationnumber:</strong>
  <%= @trip.confirmationnumber %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @trip.starttime %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @trip.startdate %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @trip.endtime %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @trip.enddate %>
</p>

<p>
  <strong>Seatnumber:</strong>
  <%= @trip.seatnumber %>
</p>

<p>
  <strong>Carrier:</strong>
  <%= @trip.carrier %>
</p>

<p>
  <strong>Type:</strong>
  <%= @trip.type %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>